name: Host Documentation

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # temporary while testing
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  # This job is called test_docs.
  build_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run unit test
        run: |
          echo "=============================================================";
          echo "Run #${GITHUB_RUN_NUMBER}";
          echo "Run ID: ${GITHUB_RUN_ID}";
          echo "Testing: ${GITHUB_REPOSITORY}";
          echo "Triggered by: ${GITHUB_EVENT_NAME}";
          echo "Initiated by: ${GITHUB_ACTOR}";
          echo "=============================================================";
          echo "=============================================================";
          echo "Create conda environment";
          echo "=============================================================";
          source $CONDA/etc/profile.d/conda.sh;
          echo $CONDA/bin >> $GITHUB_PATH;
          pip install --upgrade pip
          echo "=============================================================";
          echo "Install PETSc";
          echo "=============================================================";
          conda install -c anaconda mpi4py -q -y;
          conda install -c conda-forge petsc=3.12 petsc4py -q -y;
          echo "=============================================================";
          echo "Install OpenMDAO";
          echo "=============================================================";
          cd ..;
          pip install testflo;
          pip install redbaron
          git clone -q https://github.com/OpenMDAO/OpenMDAO;
          cd OpenMDAO;
          pip install .[all];
          cd ../mphys;
          pip install -e .
          echo "=============================================================";
          echo "List installed packages/versions";
          echo "=============================================================";
          conda list;
          cd tests/unit_tests
          testflo

      - name: Build and Commit
        uses: sphinx-notes/pages@v2

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
