name: Unit tests and docs

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Remove push when finally merging.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  # This job is called test_docs.
  test_docs:
    # Run on Ubuntu
    runs-on: ubuntu-latest

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install OpenMDAO Stack
        run: |
          echo "=============================================================";
          echo "Run #${GITHUB_RUN_NUMBER}";
          echo "Run ID: ${GITHUB_RUN_ID}";
          echo "Testing: ${GITHUB_REPOSITORY}";
          echo "Triggered by: ${GITHUB_EVENT_NAME}";
          echo "Initiated by: ${GITHUB_ACTOR}";
          echo "=============================================================";
          echo "=============================================================";
          echo "Create conda environment";
          echo "=============================================================";
          source $CONDA/etc/profile.d/conda.sh;
          echo $CONDA/bin >> $GITHUB_PATH;
          conda create -n OpenMDAO python=3.8 numpy=1.18 scipy=1.4 -q -y;
          conda activate OpenMDAO;
          echo "=============================================================";
          echo "Install PETSc";
          echo "=============================================================";
          conda install -c anaconda mpi4py -q -y;
          conda install -c conda-forge petsc=3.12 petsc4py -q -y;
          echo "=============================================================";
          echo "Install OpenMDAO";
          echo "=============================================================";
          cd ..;
          pip install -v testflo;
          which testflo
          echo "TESTFLO"
          git clone -q https://github.com/OpenMDAO/OpenMDAO;
          cd OpenMDAO;
          pip install .[all];
          cd ../mphys;
          pip install -e .
          echo "=============================================================";
          echo "List installed packages/versions";
          echo "=============================================================";
          conda list;
      - name: 'Run unit tests'
        run: |
          source $CONDA/etc/profile.d/conda.sh;
          echo $CONDA/bin >> $GITHUB_PATH;
          cd tests/unit_tests
          testflo
      - name: 'Build docs'
        run: |
          source $CONDA/etc/profile.d/conda.sh;
          echo $CONDA/bin >> $GITHUB_PATH;
          cd docs
          make html
          cd _build/html
          zip -r ./mphys.zip .
      - name: 'Upload Docs'
        uses: actions/upload-artifact@v2
        with:
          name: mphys
          path: docs/_build/html/mphys.zip
          retention-days: 7
